### ISSUE TITLE
Cannot create a task with  👀 character in the uploaded filename

### ISSUE THREAD

**Issue by azhavoro** [cvat-ai/cvat#6528]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by AndrewLuGit** [comment]
I would like to be assigned this issue

**Comment by AndrewLuGit** [comment]
The cause of this issue seems to be because of this line in `views.py`: https://github.com/opencv/cvat/blob/f22322f4349a91bbb645dfcacf1e799d870a6f16/cvat/apps/engine/views.py#L984

When there are characters that are not encodable in latin-1 such as  👀 in the file name, in the response header the file name gets encoded using MIME encoding, and so retrieving the file name from the response header can lead to unexpected results. My proposed solution is to simply decode the file name in the `_maybe_append_upload_info_entry` method, like so:
```python
def _maybe_append_upload_info_entry(self, filename: str):
    task_data = cast(Data, self._object.data)

    raw, encoding = decode_header(filename)[0]

    if encoding is not None:
        filename = raw.decode(encoding)

    filename = self._prepare_upload_info_entry(filename)
    task_data.client_files.get_or_create(file=filename)
```

**Comment by AndrewLuGit** [comment]
@nmanovic am I good to create a PR for this?

**Comment by nmanovic** [comment]
@AndrewLuGit , please do.

**Comment by azhavoro** [comment]
Fixed in https://github.com/cvat-ai/cvat/pull/7646
