### ISSUE TITLE
Vertical polyline shapes are difficult to select and move

### ISSUE THREAD

**Issue by kgloveyou** [cvat-ai/cvat#6841]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Vertical polyline shapes are difficult to select and move
### Steps to Reproduce (for bugs)

the online job is: https://app.cvat.ai/tasks/251599/jobs/258215

1.draw a vertical polyline shape
2.hover cursor to select it to move,but it‘s difficulty to select the shape.

### Expected Behaviour

it's easy to select the polyline shape.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by Andy-W-Developer** [comment]
I would like to give this a go.

### I can reproduce the issue
2 point polylines, in any direction:
I have to place my mouse exactly on the polyline to be able to select it.

3+ point polylines:
There is an area distant from the lines that allows for selection.

### Root Cause
There is not a boundary around 2 point polylines for selecting.

### Steps to fix
Look at the code for 3+ polylines and find out how the selection boundary works.
Add the boundary to 2 point polylines on all four sides.

**Comment by bsekachev** [comment]
@Andy-W-Developer 

You are welcome
