### ISSUE TITLE
How to get a analytics report right before a task is deleted

### ISSUE THREAD

**Issue by gwengusc** [cvat-ai/cvat#7837]
I am planning to use this [api](https://app.cvat.ai/api/docs/#tag/analytics/operation/analytics_get_reports)  to get reports regularly and convert them to metrics and put them on dashboard on analysis. However, I have a concern. If users delete a task, how do get the reports for the task before it is deleted? 

Let's say, I call the API every 1 hour, the user delete task within the last 1 hour before calling API happens. In this case, all the data in the last 1 hour is lost.

**Comment by bsekachev** [comment]
- You can't compute analytics report for deleted task, because part of data for the report is taken from postgres database
- All the task-related data from postgres database are removed when the task is removed.
- So, in current implementation this scenario is not supported. Only if you customize logic and will not remove task immediately after request, but after some time

**Comment by gwengusc** [comment]
Got it, thank you!
