### ISSUE TITLE
Issue with Annotation Key Points in CVAT

### ISSUE THREAD

**Issue by Sandesh-Rprocess** [cvat-ai/cvat#8117]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Expected Behavior

Hello CVAT team,

We are experiencing a problem with annotation key points. Once we finish annotating, the key points change position when we navigate to the next or previous image. Could you please investigate this issue and provide a solution.

Thank you.

Regards,
Sandesh Pavan

**Comment by Sandesh-Rprocess** [comment]
Hello CVAT Team,

I Haven't received any updated from your end, can you please provide a quick action regarding this issue.

Hoping for a positive response.

Thank you.

**Comment by bsekachev** [comment]
Hello,

It is not clear from your explanation what is the problem.
Please, provide more details: steps to reproduce, screenshots, screencast, task id, organization id, username on app.cvat.ai. 

Thank you.

**Comment by Sandesh-Rprocess** [comment]
Hello,

Please find the attachment of key point annotation screencast video and screenshot, which is being scattered while working on each task and tried with different Id's still we are facing the same issue.
[Screencast from 02-07-24 05_07_20 PM IST.webm](https://github.com/cvat-ai/cvat/assets/113497605/771ece90-4177-4eb4-99c8-d6a25f28769c)
[Screencast from 02-07-24 05_11_09 PM IST.webm](https://github.com/cvat-ai/cvat/assets/113497605/42a04fc2-41e0-4fd7-8729-707480e03dff)


![image (2)](https://github.com/cvat-ai/cvat/assets/113497605/7813bd1a-0ee3-425a-9703-b39acf52c728)
![image (3)](https://github.com/cvat-ai/cvat/assets/113497605/7ce70307-2179-48a1-96e9-894687d312b1)

Steps to reproduce:
1. Login ID: 
2. Job ID: 
3. Clonk on Skeleton keypoints

User Id's and Task Id's are mentioned below :
user Id 1: neha.anjum
Mail Id1: neha.anjum@rprocess.in
Job Id: 976523
User name 2: kusuma.cb
mail Id 2: kusuma.cb@rprocess.in
Job Id: 976498

Thank you.

**Comment by Sandesh-Rprocess** [comment]
> Hello,
> 
> It is not clear from your explanation what is the problem. Please, provide more details: steps to reproduce, screenshots, screencast, task id, organization id, username on app.cvat.ai.
> 
> Thank you.

Hello,

We have shared some data samples, screencasts and screenshots, kindly check and do the needful or do we have any possibility to sync up for call to explain this issue briefly ?

**Comment by bsekachev** [comment]
On frame 6 you have **skeleton shape** with id 592
On frame 7 you have **skeleton shape** with id 734

They are two different and independent objects because they are shapes. 
Adjusting one of them will not affect another one. 

From your description, it looks like you need to annotate skeletons using **tracks**, not **shapes**.
Please, read in CVAT documentation the difference between shapes and tracks. 

https://docs.cvat.ai/docs/manual/basics/track-mode-basics/
https://docs.cvat.ai/docs/manual/advanced/track-mode-advanced/
https://docs.cvat.ai/docs/manual/basics/shape-mode-basics/
https://docs.cvat.ai/docs/manual/advanced/shape-mode-advanced/
