### ISSUE TITLE
Need help to solve error in development environment

### ISSUE THREAD

**Issue by tsune10696** [cvat-ai/cvat#8408]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Hello,
I am trying to prepare developement environment according to [https://opencv.github.io/cvat/v2.3.0/docs/contributing/development-environment/.](https://opencv.github.io/cvat/v2.3.0/docs/contributing/development-environment/)
I'm facing the following error in debugging step of REST server in vs code.

![画像](https://github.com/user-attachments/assets/bef01a98-2b9d-4a6d-ab94-22c2ab47399a)

rest server debug error 👇
![画像 (1)](https://github.com/user-attachments/assets/addd4d8b-edb4-4131-9efa-0163142e2086)

If someone knows about that, please help me!
 
Thanks.

**Comment by azhavoro** [comment]
I can't reproduce this problem, as you can see the insecure option is supported by the runserver Django command https://docs.djangoproject.com/en/4.2/ref/contrib/staticfiles/#cmdoption-runserver-insecure as expected.

So I believe the problem is definitely in your environment.
Please provide exact steps to reproduce, including all commands, OS info, etc.
Also, why did you try to set the dev environment for 2.3.0? That's a pretty old and unreported version.
