### ISSUE TITLE
Deleted frames come back after re-opening the job

### ISSUE THREAD

**Issue by bely66** [cvat-ai/cvat#8569]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Server Version: v2.16.3
Cloud Storage: Azure Blob Storage (seems that's irrelevant because the issue happens with local storage too)

1. Delete any frame from a job using the delete button or Alt + del
2. The frame will disappear inside your session
3. Once you refresh the task the image/frame will comeback to the job
4. I made sure that show deleted frames is unselected in my settings

### Expected Behavior

Deleted frames should persist in the memory as deleted and not comeback

### Possible Solution

No idea but seems the deleted frames doesn't make it through to the Backend from the UI for some reason.

**Comment by bsekachev** [comment]
You need to save the job first.

**Comment by davy-blavette** [comment]
Hello,

I've got the same problem, the frames won't delete. On the task the number of frames doesn't change, and if you export you have all the images in the project... the only change is the navigation between the frames, otherwise I don't see what the delete button is for?

![Image](https://github.com/user-attachments/assets/3a113e70-7c24-4a27-bcee-2bab134610ce)
