### ISSUE TITLE
issues labels

### ISSUE THREAD

**Issue by lolo-05** [cvat-ai/cvat#8756]
Good afternoon, in the previous version of CVAT, I could change the numbers assigned to the labels for quick label switching, making annotation faster. How do I change this in the new version? Thanks in advance, best regards

![Captura de pantalla 2024-11-28 144027](https://github.com/user-attachments/assets/c932a85b-3315-41c8-8cf9-671a7182104b)

**Comment by bsekachev** [comment]
This functionality was removed because it was misunderstood by many users.

We implemented a shortcuts customization mechanism, but it still does not fully cover the functionality when there are more than 10 labels.

To track progress on this issue, please refer to https://github.com/cvat-ai/cvat/issues/8604. I will close this one as a duplicate.
